name: Run Lighthouse on Mobile

on:
  schedule:
    - cron: "0 14 * * *"  # Daily at 10am EST
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Run Lighthouse CI
        id: lhci
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: 'https://pizazzdesign.com'
          configPath: './lighthouserc.json'
          uploadArtifacts: true

      - name: Upload Lighthouse report
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: '.lighthouseci/*'
